name: lib_msaadev
description: my first custom package to write codes easily
version: 0.0.1
homepage: https://github.com/msaadev/lib_msaadev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.4
  mask_text_input_formatter: ^2.0.0
  share: ^2.0.4
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
